### ISSUE TITLE
Can't disable network interface

### ISSUE THREAD

**Issue by alexiri** [home-assistant/cli#333]
## Describe the problem

It's not possible to disable a network interface. There's a `ha network update --enabled`, but there's no equivalent `--disabled`.

## Debug information

1. SSH Addon type

- [ ] Community
- [X] Core
- [ ] Custom

2. Version of the CLI

CLI Version: 2021.12.0
Add-on: 
Add-on version: 

3. Version of Home Assistant Core & the Home Assistant Supervisor

Home Assistant Core: 2022.2.9
Home Assistant Supervisor: 2022.01.1

4. Output from executing the command with debug info

e.g., `ha hardware info` should be run as `ha --log-level debug hardware info`
```txt

```

## Expected behavior

I would like to be able to disable a network interface via `ha network update --disabled wlan0`.

## Additional context

The closest I've managed to get was `ha network update wlan0 --ipv4-method disabled --ipv6-method disabled`, so the interface doesn't get an IP, but it is still online.

**Comment by bremme** [comment]
Damn, I just spend one hour pulling my hair out because of this as well :laughing: I'm using the exact same versions:

* CLI Version: 2021.12.0
* Home Assistant Core: 2022.2.9
* Home Assistant Supervisor: 2022.01.1

I tried everything I could think of, but no success. It guess it should be `ha network update wlan0 --enabled false` since the default is `true`.
